[package]
name = "mailersend"
version = "0.1.0"
edition = "2018"
author = "meh. <meh@confidential.portal.film>"

[dependencies]
reqwest = "0.11"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
