[package]
name = "mailersend"
version = "0.1.1"
edition = "2018"

authors = ["meh. <meh@confidential.portal.film>"]
license = "Apache-2"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
