[package]
name = "mailersend"
version = "0.1.0"
edition = "2018"
author = "meh. <meh@confidential.portal.film>"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
thiserror = "1"
